### ISSUE TITLE
FengYun-3 AHRPT Deframer out of sync

### ISSUE THREAD

**Issue by Foxiks** [altillimity/SatDump#132] opened 2022-09-18 07:08 UTC
![253414253](https://user-images.githubusercontent.com/61653684/190890001-8a38e21f-41fa-4bd7-9913-a8e20bbc2d25.png)
The AHRPT decoder for the FY-3B has no sync for the deframer, while the Viterbi syncs.

**Comment by Aang23** [comment] 2022-09-18 09:41
Ok. I remember I forgot to fix that one... One of the tiny differences between FY's behavior on L and X-Band.

Will be fixed up. Didn't test FY-3B L-Band as much as it's not active anymore, and 3C is pretty challenging from Europe!

**Closed** 2022-09-18 09:45 UTC
Labels: bug, DSP

**Comment by Foxiks** [comment] 2022-09-18 15:20
Unfortunately this still doesn't work. Same problem with Metop

**Comment by Aang23** [comment] 2022-09-18 15:21
Uh what? Can you send the basebands? Didn't see that even once until now.

**Comment by Foxiks** [comment] 2022-09-18 15:22
Yes, give me 15-20 minutes to upload

**Comment by Foxiks** [comment] 2022-09-18 15:30
![image](https://user-images.githubusercontent.com/61653684/190914787-29475d95-d3c9-4cd1-bee1-19b69fb1c795.png)
https://drive.google.com/file/d/1g0HiZPSOMrxUOgKx-N5og3Wk5yQsgUgT/view?usp=sharing MetOp

**Comment by Aang23** [comment] 2022-09-18 15:33
![Screenshot from 2022-09-18 17-32-44](https://user-images.githubusercontent.com/23421917/190915229-811d3657-e164-48d3-a64a-d5e4fb608feb.png)

**Comment by Aang23** [comment] 2022-09-18 15:33
Oh wait! This may not be a bug in the decoders at all. It may be related to the recorder's scrolling behaviour perhaps.

**Comment by Foxiks** [comment] 2022-09-18 15:37
Hm this works a little weird. Look at this. https://youtu.be/tvQuw8sFX9w

**Comment by Aang23** [comment] 2022-09-18 15:38
Yep. That's what I am talking about actually! Will wait to check with FY and debug.

**Comment by Foxiks** [comment] 2022-09-18 15:40
the same with FY. Deframer for FY works the same as with metop

**Comment by Aang23** [comment] 2022-09-18 15:44
I see. I think I know why. It's a bug that can only occur when replaying a baseband and not when on an actual signal.
I'll wait for the FY baseband to check still, but otherwise I'm already thinking of a few ways to fix that properly.

**Comment by Foxiks** [comment] 2022-09-18 15:53
Also, sometimes during offline decoding from IQ recording, the deframer shows the "syncing" status and this is very strongly reflected in the photo. The previous version of satdump does not have this problem.

**Comment by Aang23** [comment] 2022-09-18 16:15
I've gotten a fix implemented for MetOp (again, it's a behaviour that only happens because the demodulator is suddenly fed a strong signal, strong enough for the Viterbi to lock on the wrong state). I'm gonna test on FY to confirm everything works before I push though.

**Comment by Aang23** [comment] 2022-09-18 16:40
Just pushed some fixes. Should have helped.

**Comment by Foxiks** [comment] 2022-09-18 16:46
Excellent! Thank you!

**Comment by Foxiks** [comment] 2022-09-19 20:43
![image](https://user-images.githubusercontent.com/61653684/191112594-b18d3e52-09f7-4527-a4f2-1875fd40fda7.png)
Sometimes, after a momentary loss of signal, the deframer goes into the "syncing" status. It does not depend on signal strength

**Comment by Aang23** [comment] 2022-09-19 20:44
Do you have a baseband sample of that happening so I can test here? Could not see that with any of my basebands.

**Comment by Foxiks** [comment] 2022-09-19 20:45
Yes. But I need to upload this... Give me some time)

**Comment by Aang23** [comment] 2022-09-19 20:46
No worries! I will wait! Thanks

**Comment by Foxiks** [comment] 2022-09-19 20:56
Unfortunately, my entry has a weight of more than 26 GB. I won't be able to upload it today and will upload it tomorrow

**Comment by Aang23** [comment] 2022-09-19 20:57
No problem!
You can use https://www.swisstransfer.com if necessary.

**Comment by Foxiks** [comment] 2022-09-20 17:27
unfortunately i have a very low speed for [swisstransfer](https://www.swisstransfer.com/). I will upload it throughout tomorrow

**Comment by Aang23** [comment] 2022-09-20 20:02
No worries!

**Comment by Foxiks** [comment] 2022-09-21 09:25
https://drive.google.com/file/d/1odzinGOBnT1_cCbYweuNT1vwjcl_vTGf/view?usp=sharing

**Comment by Aang23** [comment] 2022-09-21 09:52
Hmmm interestingly enough, here it did *not* unlock even once (apart from the few sampledrops here and there). I will test on Windows, maybe the issue is specific there.

**Comment by Aang23** [comment] 2022-09-21 10:06
Just to clarify : Whenever you see a spike like this it due to sampledrop in the baseband : so because your SSD/HDD was not fast enough to save what you were recording. Nothing I can do fix that unfortunately!

![Screenshot from 2022-09-21 12-00-44](https://user-images.githubusercontent.com/23421917/191476003-0aa941b7-56bc-49a2-8075-691d5661e396.png)
![Screenshot from 2022-09-21 12-04-39](https://user-images.githubusercontent.com/23421917/191476835-afaa5e1f-125e-4465-9518-aa8747058824.png)

Otherwise, everything seems mostly fine. Still re-tuning some things and gonna do a bit more testing though.

**Comment by Foxiks** [comment] 2022-09-21 10:50
Hm, okay. But for me, after such a "burst", sometimes the deframer does not receive normal data and goes into the "SYNCING" status

**Comment by Aang23** [comment] 2022-09-21 10:54
It also does here (which is expected), but does stay stuck in SYNCING state. I will try on Windows soon.

**Comment by Foxiks** [comment] 2022-09-21 13:03
okay
