### ISSUE TITLE
AirSpy-R2 10M ok, 2.5M error

### ISSUE THREAD

**Issue by K4KDR** [altillimity/SatDump#57] opened 2021-10-30 00:15 UTC
After downloading the updated v0.0.38 code, I can now run 'Live Processing' with my Airspy-R2 at the 10M sample rate setting, but if I enter 2.5M, I get the following:

-------------------------------------------------------------------------------------------
```
[10/30/21 - 00:06:23] (E) No settings file found! Using defaults.
[10/30/21 - 00:06:40] (D) Starting livedemod...
[10/30/21 - 00:06:42] (D) Opening file dialog
[10/30/21 - 00:06:50] (D) Dir /home/k4kdr/SatDump-0.0.38/OUTPUT
[10/30/21 - 00:06:51] (D) Starting livedemod...
[10/30/21 - 00:06:51] (I) meteor_m2_lrpt
[10/30/21 - 00:06:51] (I) Starting live pipeline METEOR M2 LRPT
[10/30/21 - 00:06:51] (I) Module qpsk_demod
[10/30/21 - 00:06:51] (D) Parameters :
[10/30/21 - 00:06:51] (D)    - agc_rate : 0.1
[10/30/21 - 00:06:51] (D)    - baseband_format : f32
[10/30/21 - 00:06:51] (D)    - buffer_size : 8192
[10/30/21 - 00:06:51] (D)    - costas_bw : 0.004
[10/30/21 - 00:06:51] (D)    - dc_block : 0
[10/30/21 - 00:06:51] (D)    - rrc_alpha : 0.6
[10/30/21 - 00:06:51] (D)    - rrc_taps : 361
[10/30/21 - 00:06:51] (D)    - samplerate : 2500000
[10/30/21 - 00:06:51] (D)    - symbolrate : 72000
[10/30/21 - 00:06:51] (I) Module meteor_lrpt_decoder
[10/30/21 - 00:06:51] (D) Parameters :
[10/30/21 - 00:06:51] (D)    - baseband_format : f32
[10/30/21 - 00:06:51] (D)    - dc_block : 0
[10/30/21 - 00:06:51] (D)    - diff_decode : 0
[10/30/21 - 00:06:51] (D)    - samplerate : 2500000
[10/30/21 - 00:06:51] (T) Volk has the spiral kernel, using it!
[10/30/21 - 00:06:51] (D) Starting SDR...
[10/30/21 - 00:06:51] (D) Device parameters airspy:
[10/30/21 - 00:06:51] (I) Opened Airspy device!
[10/30/21 - 00:06:51] (I) Samplerate 2500000.000000
[10/30/21 - 00:06:51] (I) Frequency 137100000.000000
[10/30/21 - 00:06:51] (D) Input SPS : 34.722221
[10/30/21 - 00:06:51] (D) Resample : 1
[10/30/21 - 00:06:51] (D) Samplerate : 210000.000000
[10/30/21 - 00:06:51] (D) Dec factor : 11.904762
[10/30/21 - 00:06:51] (D) Final SPS : 2.916667
corrupted size vs. prev_size
Aborted (core dumped)
```
-------------------------------------------------------------------------------------------

... as you can see at the top of that dump, I deleted my **settings.json** file to make sure that nothing saved in there was causing this issue.

FYI, the image files that resulted from the 'Live' 10M capture appeared normal, but it would be great to be able to run with the 2.5M sample rate to have a more useful FFT display and to reduce the system load on the computer.

Many thanks!     -Scott,  K4KDR

**Comment by Aang23** [comment] 2021-10-30 13:36
That is very weird, 2.5M works just fine here.

Can you try using the latest code on Github first to be sure?

**Comment by K4KDR** [comment] 2021-10-30 17:55
Many thanks for the recommendation!

The result was the same... 10M sample rate runs normally; 2.5M fails (output below)

```
[10/30/21 - 17:50:50] (D) Starting livedemod...
[10/30/21 - 17:50:50] (I) Generated folder name : /home/k4kdr/SatDump/output/2021-10-30_17-50_meteor_m2_lrpt_137Mhz
[10/30/21 - 17:50:50] (I) meteor_m2_lrpt
[10/30/21 - 17:50:50] (I) Starting live pipeline METEOR M2 LRPT
[10/30/21 - 17:50:50] (I) Module qpsk_demod
[10/30/21 - 17:50:50] (D) Parameters :
[10/30/21 - 17:50:50] (D)    - agc_rate : 0.1
[10/30/21 - 17:50:50] (D)    - baseband_format : f32
[10/30/21 - 17:50:50] (D)    - buffer_size : 8192
[10/30/21 - 17:50:50] (D)    - costas_bw : 0.004
[10/30/21 - 17:50:50] (D)    - dc_block : 0
[10/30/21 - 17:50:50] (D)    - rrc_alpha : 0.6
[10/30/21 - 17:50:50] (D)    - rrc_taps : 361
[10/30/21 - 17:50:50] (D)    - samplerate : 2500000
[10/30/21 - 17:50:50] (D)    - symbolrate : 72000
[10/30/21 - 17:50:50] (I) Module meteor_lrpt_decoder
[10/30/21 - 17:50:50] (D) Parameters :
[10/30/21 - 17:50:50] (D)    - baseband_format : f32
[10/30/21 - 17:50:50] (D)    - dc_block : 0
[10/30/21 - 17:50:50] (D)    - diff_decode : 0
[10/30/21 - 17:50:50] (D)    - samplerate : 2500000
[10/30/21 - 17:50:50] (T) Volk has the spiral kernel, using it!
[10/30/21 - 17:50:50] (D) Starting SDR...
[10/30/21 - 17:50:50] (D) Device parameters airspy:
[10/30/21 - 17:50:50] (I) Opened Airspy device!
[10/30/21 - 17:50:50] (I) Samplerate 2500000.000000
[10/30/21 - 17:50:50] (I) Frequency 137100000.000000
[10/30/21 - 17:50:50] (D) Input SPS : 34.722221
[10/30/21 - 17:50:50] (D) Resample : 1
[10/30/21 - 17:50:50] (D) Samplerate : 210000.000000
[10/30/21 - 17:50:50] (D) Dec factor : 11.904762
[10/30/21 - 17:50:50] (D) Final SPS : 2.916667
[10/30/21 - 17:50:50] (I) Start processing...
[10/30/21 - 17:50:50] (I) Start processing...
[10/30/21 - 17:50:50] (I) Using input baseband 
[10/30/21 - 17:50:50] (I) Demodulating to /home/k4kdr/SatDump/output/2021-10-30_17-50_meteor_m2_lrpt_137Mhz/meteor_m2_lrpt.soft
[10/30/21 - 17:50:50] (I) Buffer size : 98304
[10/30/21 - 17:50:50] (I) Using input symbols 
[10/30/21 - 17:50:50] (I) Decoding to /home/k4kdr/SatDump/output/2021-10-30_17-50_meteor_m2_lrpt_137Mhz/meteor_m2_lrpt.cadu
Segmentation fault (core dumped)

k4kdr@3010i5:~/SatDump/build$ git branch
* master
```

**Comment by Aang23** [comment] 2021-10-30 18:55
What are you attempting to do exactly? Because I cannot reproduce it anymore here...

**Comment by K4KDR** [comment] 2021-10-30 19:18
Running satdump-ui, 'Live Processing', Meteor M2 LRPT, 2.5M Sample Rate

![satdump-0 0 38-2 5M](https://user-images.githubusercontent.com/19886368/139555873-28999874-f160-487a-94f2-b4c3d1fc56ad.png)

**Comment by KentuckyFriedData** [comment] 2021-10-30 21:34
I can reproduce this as well and get

![Screenshot_2021-10-30_14-32-17](https://user-images.githubusercontent.com/31137660/139558938-00eaf4f5-9bba-4278-ab17-efe13ccfd489.png)

i have even included logs below

[gdb-debug.txt](https://github.com/altillimity/SatDump/files/7447635/gdb-debug.txt)
[valgrind-debug.txt](https://github.com/altillimity/SatDump/files/7447636/valgrind-debug.txt)

**Comment by Aang23** [comment] 2021-11-01 22:36
That is the exact bug I fixed recently. I will try to reproduce on Ubuntu 18.4 I guess... Can't on my machine.

**Comment by Aang23** [comment] 2021-11-06 01:34
Actually, https://github.com/altillimity/SatDump/commit/01a8276de8c18cf24f455919abb44a9d7dc2ec10 may also have fixes this issue. Would anyone be able to confirm?

**Comment by K4KDR** [comment] 2021-11-06 01:51
Will update now & check on tomorrow's pass.

Many thanks!

**Comment by K4KDR** [comment] 2021-11-06 02:40
Sorry - don't need a satellite to test whether it crashes w/ the 2.5M Sample Rate or not.

Works great!   Thanks so much for the update.  Can run 'Live' w/ the 2.5M rate again.

![satdump-ui-0 0 38-2 5M](https://user-images.githubusercontent.com/19886368/140595182-931017a0-7f42-4f3d-a34f-236ca28b4e26.png)

**Comment by K4KDR** [comment] 2021-11-06 12:49
[v0.0.38 / master branch / build: 01a8276, built from source]

Running 'Live Processing' with Airspy-R2 @ 2.5M Sample Rate:

satdump-ui 'Live Processing' ran properly with the **2.5M Sample Rate** - thank you!!


![GUI](https://user-images.githubusercontent.com/19886368/140610192-acc6fb20-7cac-4d63-8bf2-e4fdca11be56.png)

**Comment by Aang23** [comment] 2021-11-28 12:20
I guess I can close this now!

**Closed by Aang23** 2021-11-28 12:20 UTC
